CREATE SEQUENCE building_seq
    START WITH 1
    INCREMENT BY 1;
    
CREATE SEQUENCE class_seq
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE course_seq
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE faculty_seq
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE department_seq
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE curriculum_seq
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE pl_seq
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE student_seq
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE teacher_seq
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE section_info_seq
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE seqtion_seq
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE entry_seq
    START WITH 1
    INCREMENT BY 1;