INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 61, 'Computer Engineering', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 61, 'Computer Engineering', 2);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 61, 'Computer Engineering', 3);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 61, 'Electrical and Electronics Engineering', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 61, 'Electrical and Electronics Engineering', 2);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 61, 'Electrical and Electronics Engineering', 3);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 61, 'Industrial Engineering', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 61, 'Industrial Engineering', 2);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 61, 'Industrial Engineering', 3);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 61, 'Mechanical Engineering', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 61, 'Mechanical Engineering', 2);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 61, 'Mechanical Engineering', 3);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 62, 'Architecture', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 62, 'Architecture', 2);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 62, 'Communication and Design', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 62, 'Communication and Design', 2);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 62, 'Fine Arts', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 62, 'Graphic Design', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 62, 'Interior Architecture and Environmental Design', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 62, 'Interior Architecture and Environmental Design', 2);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 62, 'Interior Architecture and Environmental Design', 3);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 62, 'Urban Design and Landscape Architecture', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 63, 'Management', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 63, 'Management', 2);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 63, 'Management', 3);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 64, 'Economics', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 64, 'Economics', 2);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 64, 'Economics', 3);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 64, 'History', 2);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 64, 'History', 3);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 64, 'International Relations', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 64, 'International Relations', 2);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 64, 'International Relations', 3);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 64, 'Global International Affairs', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 64, 'Political Science and Public Administration', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 64, 'Political Science and Public Administration', 2);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 64, 'Political Science and Public Administration', 3);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 64, 'Psychology', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 64, 'Psychology', 2);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 64, 'Psychology', 3);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 67, 'American Culture and Literature', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 67, 'Archaeology', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 67, 'Archaeology', 2);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 67, 'English Language and Literature', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 67, 'Translation and Interpretation', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 67, 'Philosophy', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 67, 'Philosophy', 2);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 68, 'Law', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 68, 'Law', 2);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 68, 'Law', 3);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 69, 'Music', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 69, 'Music', 2);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 69, 'Performing Arts', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 70, 'Chemistry', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 70, 'Chemistry', 2);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 70, 'Chemistry', 3);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 70, 'Mathematics', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 70, 'Mathematics', 2);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 70, 'Mathematics', 3);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 70, 'Molecular Biology and Genetics', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 70, 'Molecular Biology and Genetics', 2);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 70, 'Molecular Biology and Genetics', 3);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 70, 'Physics', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 70, 'Physics', 2);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 70, 'Physics', 3);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 71, 'Accounting Information Systems', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 71, 'Banking and Finance', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 72, 'Business Information Management', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 72, 'Computer Technology and Information Systems', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 72, 'Tourism and Hotel Management', 1);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 75, 'Energy Economics, Policy, and Security', 2);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 75, 'Materials Science and Nanotechnology', 3);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 75, 'Neuroscience', 2);
INSERT INTO department( faculty_no, department_name, degree_no) VALUES ( 75, 'Neuroscience', 3);
